# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    paths:
      - 'Server/**'
      - '.github/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: ./Server
      run: |
        mvn clean compile 
        mvn package
    - name: Upload Server.jar compiled file
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: Server
      # Directory containing files to upload
        path: ./Server/target/tomcat-embedded-example-1.0-SNAPSHOT.jar
